version: "3.7"

services:
  memcached:
    image: memcached:1.6.10-alpine
    restart: always
    ports:
      - "11211:11211"

  redis:
    image: redis:6.2.6-alpine
    restart: always
    ports:
      - "6379:6379"
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf

  postgres:
    image: postgres:9.6-bullseye
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: root
